name: Build

on:
  push:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    container: wpilib/roborio-cross-ubuntu:2023-22.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Grant execute permission
      run: chmod +x gradlew
    - name: Check formatting
      run: ./gradlew spotlessCheck
    - name: Build and test
      run: ./gradlew build