name: Build

on:
  push:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    container: wpilib/roborio-cross-ubuntu:2023-22.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"
    - name: Install Python dependencies
      shell: bash
      run: |
        python -m venv venv
        source ./venv/bin/activate
        pip install -r requirements.txt
    - name: Grant execute permission
      run: chmod +x gradlew
    - name: Check formatting
      run: ./gradlew spotlessCheck
    - name: Build and test
      run: ./gradlew build